const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const percent=v=>v==null?'Unknown':`${Math.round(v*100)}%`;
export function evidenceSummary(r){
 const m=r.bestMatch,s=r.structure;
 const position=!r.domainEvidence.boundaryVerified?'LRR-region boundary unknown':m?.proximalVerified?'Within the existing ±50-aa LRR-start window':'No preferred qualifying motif within the verified proximal window';
 const motif=m?`${m.sequence} at ${m.start}–${m.end}; ${percent(m.identity)} identity and ${percent(m.conservation)} conservative similarity`:'No qualifying NLEEL-like motif';
 const structure=s?.status==='measured'?`${s.totalPairs} WHD–LRR residue-pair contacts ≤ ${s.cutoff} Å; WHD coverage ${percent(s.whdCoverage)}, LRR coverage ${percent(s.lrrCoverage)}. Contact count alone has no established TS/TT direction.`:s?.reason??'No measured WHD–LRR interface available. A matching structure and annotated boundaries are needed.';
 return `<details class="evidence-summary"><summary>Evidence summary and proposed weighting</summary><p>Draft candidate-prioritization framework. These weights are not active in the frozen classifier.</p><div class="table-wrap"><table><thead><tr><th>Step</th><th>Available evidence</th><th>Proposed weight</th></tr></thead><tbody><tr><td>1. LRR-proximal motif and similarity</td><td>${esc(position)}. ${esc(motif)}.</td><td>50%</td></tr><tr><td>2. Evolutionary conservation</td><td>Not assessed. Requires a homolog multiple-sequence alignment. Conservative substitution similarity and the two reference comparisons are not independent evolutionary-conservation evidence.</td><td>25%</td></tr><tr><td>3. Structural interface evidence</td><td>${esc(structure)}</td><td>25%</td></tr><tr><td>4. Evidence classification</td><td>Current sequence-only call: ${esc(r.classification.label)}. Current integrated call: ${esc(r.integrated.label)}; ${esc(r.integrated.basis)}.</td><td>Output, not a scored input</td></tr></tbody></table></div><p class="tiny">Weighted total: not calculated. Missing evidence remains unknown. The proposed weights require calibration and independent testing; more contacts do not automatically mean greater stability or temperature tolerance. Curated phenotypes and existing classifications are not fed back into this proposed score. Phase 3 data and rules remain unchanged.</p></details>`;
}
