export function delimited(rows,delimiter="\t") {
  const cell=value=>{
    let s=String(value??"");if(/^[=+@-]/.test(s))s="'"+s;
    return delimiter===","?`"${s.replace(/"/g,'""')}"`:s.replace(/[\t\r\n]+/g," ");
  };return rows.map(row=>row.map(cell).join(delimiter)).join("\n");
}
export function resultsTable(results,delimiter) {
  const header=["sequence_id","ruleset","length_aa","nlr_class","first_lrr_start","boundary_source","first_lrr_end","annotated_lrr_repeat_count","total_nleel_hits","lrr_region_nleel_hits","first_lrr_nleel_hits","first_lrr_has_nleel","proximal_nleel_hits","hit_repeat_positions","preferred_motif","start","end","second_e_residue","identity_percent","conservation_percent","distance_to_lrr","most_conserved","nearest_to_lrr","all_nleel_hits","interface_segments","local_interface_segments","sequence_call","integrated_call","call_basis","phenotype_references","whd_lrr_contact_pairs","structure_status","explanation","selection_reason","domain_annotations","reference_window_comparisons","lrr_region_start","lrr_region_end","lrr_region_source","near_lrr_start_verified","domain_job_id","reference_context_rule","reference_context_status","reference_context_motif","reference_context_start","reference_context_end","reference_second_e_equivalent","reference_context_explanation"];
  const motif=m=>m?`${m.sequence}:${m.start}-${m.end}`:"";
  return delimited([header,...results.map(r=>[r.id,r.ruleset,r.length,r.domainEvidence.nlrClass,r.domainEvidence.firstLrrStart,r.domainEvidence.boundarySource,r.domainEvidence.firstLrrEnd,r.rankings.summary.repeatCount??"Unknown",r.rankings.summary.totalHits,r.rankings.summary.lrrHits??"Unknown",r.rankings.summary.firstLrrHits??"Unknown",r.rankings.summary.firstLrrStatus,r.rankings.summary.proximalHits??"Unknown",r.matches.map(m=>`${motif(m)}:LRR=${m.repeatIndices.join("|")||"unassigned"}:overlap=${m.overlappingRepeatIndices.join("|")||"unassigned"}`).join(";"),r.bestMatch?.sequence,r.bestMatch?.start,r.bestMatch?.end,r.bestMatch?.secondEResidue,r.bestMatch?Math.round(r.bestMatch.identity*100):"",r.bestMatch?Math.round(r.bestMatch.conservation*100):"",r.bestMatch?.distanceToFirstLrr,motif(r.rankings.mostConserved),motif(r.rankings.nearest),r.matches.map(motif).join(";"),r.interfaceEvidence.hits.map(motif).join(";"),r.interfaceEvidence.localHits.map(motif).join(";"),r.classification.label,r.integrated?.label,r.integrated?.basis,r.integrated?.phenotypes.map(p=>p.reference).join(";"),r.structure?.status==="measured"?r.structure.totalPairs:"",r.structure?.status??"not assessed",`${r.classification.explanation} ${r.integrated?.explanation??""}`,r.rankings.selectionReason,JSON.stringify(r.domainEvidence.domains??[]),JSON.stringify((r.referenceComparisons??[]).map(c=>({reference:c.ref.id,status:c.ref.status,query:c.best?.hit.start,identity:c.best?.alignment.identity,coverage:c.best?.alignment.coverage,secondEEquivalent:c.best?.mapped,tied:c.tied}))),r.domainEvidence.lrrRegionStart,r.domainEvidence.lrrRegionEnd,r.domainEvidence.lrrRegionSource,r.bestMatch?.proximalVerified,r.domainEvidence.domainJob?.id,r.referenceContext?.rule,r.referenceContext?.status,r.referenceContext?.motif,r.referenceContext?.start,r.referenceContext?.end,r.referenceContext?.secondE,r.referenceContext?.reason])],delimiter);
}
