import {domainKind} from './domain-jobs.mjs';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function numberedSequence(sequence,hits=[],offset=1){
 const rows=[];for(let i=0;i<sequence.length;i+=50){let body='';for(let j=i;j<Math.min(i+50,sequence.length);j++){const p=j+offset,h=hits.find(h=>p>=h.start&&p<=h.end);body+=`<span${h?` class="${p===h.start+3?'second-e':'motif'}" title="${esc(h.sequence)} ${h.start}–${h.end}; residue ${p}"`:''}>${sequence[j]}</span>`;if((j-i+1)%10===0)body+=' ';}rows.push(`<div class="sequence-row"><span class="coordinate">${i+offset}</span><span>${body}</span><span class="coordinate">${Math.min(i+50,sequence.length)+offset-1}</span></div>`);}return rows.join('');
}
export function architecture(r,index){
 const d=r.domainEvidence,rows=[];
 const overview=(d.domains??[]).filter(x=>['NB-ARC','Kinase','TIR'].includes(domainKind(x))).filter((x,i,a)=>a.findIndex(y=>domainKind(y)===domainKind(x))===i);
 if(d.lrrRegionStart!=null)overview.push({name:'LRR region',start:d.lrrRegionStart,end:d.lrrRegionEnd??r.length});
 rows.push(`<div class="architecture-row overview-row"><strong>Domain overview</strong><div class="architecture-track">${overview.map(x=>`<span class="architecture-domain overview-domain" style="left:${(x.start-1)/r.length*100}%;width:${(x.end-x.start+1)/r.length*100}%" title="${esc(x.name)} ${x.start}–${x.end}">${esc(x.name==='LRR region'?'LRR':domainKind(x))}</span>`).join('')}</div></div>`);

 const lane=(name,items,cls='')=>`<div class="architecture-row"><span>${esc(name)}</span><div class="architecture-track">${items.map(x=>`<span class="architecture-domain ${cls}" style="left:${(x.start-1)/r.length*100}%;width:${(x.end-x.start+1)/r.length*100}%" title="${esc(x.name??name)} ${x.start}–${x.end}; ${esc(x.source??d.boundarySource)}"></span>`).join('')}</div></div>`;
 for(const x of d.domains??[])rows.push(lane(`${x.name} ${x.start}–${x.end}`,[x],/LRR|leucine/i.test(x.name)?'lrr':'supported'));
 if(!(d.domains??[]).some(x=>/NB.ARC/i.test(x.name))&&d.heuristicDomains.nbArc)rows.push(lane('NB-ARC estimate',[d.heuristicDomains.nbArc],'estimate'));
 if(d.heuristicDomains.lrr)rows.push(lane(d.boundaryVerified?'LRR annotation':'LRR estimate',[d.heuristicDomains.lrr],d.boundaryVerified?'lrr':'estimate'));
 if(d.lrrRepeats.length)rows.push(lane('Individual LRR repeats',d.lrrRepeats,'repeat'));
 if(d.lrrRegionStart!=null)rows.push(`<div class="architecture-row"><strong>LRR region start: ${d.lrrRegionStart}</strong><div class="architecture-track"><span class="lrr-start-marker" style="left:${(d.lrrRegionStart-1)/r.length*100}%"></span><span class="proximal-band" style="left:${Math.max(0,d.lrrRegionStart-51)/r.length*100}%;width:${(Math.min(r.length,d.lrrRegionStart+50)-Math.max(1,d.lrrRegionStart-50)+1)/r.length*100}%"></span></div></div>`);
 if(d.firstLrrEnd)rows.push(lane(`LRR 1: ${d.firstLrrStart}–${d.firstLrrEnd}`,[{start:d.firstLrrStart,end:d.firstLrrEnd,source:d.repeatBoundarySource}],'first'));
 if(d.whd)rows.push(lane('WHD',[d.whd],'whd'));
 rows.push(`<div class="architecture-row"><span>NLEEL-like motifs</span><div class="architecture-track">${r.matches.map(m=>`<button class="architecture-hit ${m.start===r.bestMatch?.start?'preferred':''}" data-protein="${index}" data-hit="${m.start}" style="left:${(m.start-1)/r.length*100}%" title="${esc(m.sequence)} ${m.start}–${m.end}${m.start===r.bestMatch?.start?'; preferred':''}" aria-label="Inspect ${esc(m.sequence)} at ${m.start}"></button>`).join('')}</div></div>`);
 return `<div class="architecture">${rows.join('')}<div class="architecture-row"><span>Residue coordinates</span><div class="architecture-axis"><span>1</span><span>${Math.round(r.length/2)}</span><span>${r.length}</span></div></div></div><p class="tiny">Blue: source-supported domains · dashed: sequence estimates · teal: LRR 1 · orange motif marker: preferred. Click any motif marker or table entry to inspect its window. No domain shown means unavailable annotation, not proven absence.</p><details><summary>Domain sources and coordinates</summary><div class="table-wrap"><table><thead><tr><th>Domain</th><th>Coordinates</th><th>Source</th><th>Accession</th></tr></thead><tbody>${(d.domains??[]).map(x=>`<tr><td>${esc(x.name)}</td><td>${x.start}–${x.end}</td><td>${esc(x.source)}</td><td>${esc(x.accession)}</td></tr>`).join('')}</tbody></table></div><p>${esc(d.boundarySource)}</p></details>`;
}
export function referenceHtml(comparisons,r){return comparisons.map(({ref,best,start,end,tied})=>`<div class="reference-comparison"><h4>${esc(ref.id)} reference</h4><p>${esc(ref.status)}</p><p class="tiny">${esc(ref.conditions)} · ${esc(ref.assay)}. Stored reference sequence/allele: ${esc(ref.sequenceSource??('RefPlantNLR '+ref.id))}; experimental allele mapping is stated above.</p>${best?`<p>Best window alignment: ${best.hit.sequence} ${best.hit.start}–${best.hit.end}${best.hit.start!==r.bestMatch?.start?' · differs from positional preferred candidate':''}${tied?' · multiple equally scoring windows':''}. Aligned identity ${Math.round(best.alignment.identity*100)}%; paired-residue coverage ${Math.round(best.alignment.coverage*100)}%. Second-E-equivalent alignment maps to ${best.mapped==null?'a gap':`${r.sequence[best.mapped-1]}${best.mapped}`}; ${best.mapped===best.hit.start+3?'matches':'does not match'} candidate second-E position.</p><div class="alignment"><div>Reference ${start}–${end}</div><pre>${esc(best.alignment.reference)}\n${[...best.alignment.reference].map((x,i)=>x!=='-'&&x===best.alignment.query[i]?'|':' ').join('')}\n${esc(best.alignment.query)}</pre><div>Query ${best.queryStart}–${best.queryEnd}</div></div><p class="tiny">Reference motif Δ annotated LRR start: ${ref.annotation?.firstLrrStart!=null?ref.anchor-ref.annotation.firstLrrStart:'unknown'} aa; query: ${best.hit.distanceToFirstLrr??'unknown'} aa. Alignment is exploratory correspondence; it does not establish functional homology or transfer temperature sensitivity. LRR repeat numbering may differ between annotation methods.</p>`:'<p>No qualifying query motif window to align.</p>'}</div>`).join('');}
